### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by ehernandez-xk** [evnix/boltdbweb#1]
Hi, Following the instructions I get

`boltdbweb my.db 8080`

Browser:

http://localhost:8080/web/html/
404 page not found

[GIN-debug] GET    /ping                     --> main.main.func1 (3 handlers)
[GIN-debug] GET    /                         --> github.com/evnix/boltdbweb/web.Index (3 handlers)
[GIN-debug] GET    /buckets                  --> github.com/evnix/boltdbweb/web.Buckets (3 handlers)
[GIN-debug] POST   /createBucket             --> github.com/evnix/boltdbweb/web.CreateBucket (3 handlers)
[GIN-debug] POST   /put                      --> github.com/evnix/boltdbweb/web.Put (3 handlers)
[GIN-debug] POST   /get                      --> github.com/evnix/boltdbweb/web.Get (3 handlers)
[GIN-debug] POST   /deleteKey                --> github.com/evnix/boltdbweb/web.DeleteKey (3 handlers)
[GIN-debug] POST   /deleteBucket             --> github.com/evnix/boltdbweb/web.DeleteBucket (3 handlers)
[GIN-debug] POST   /prefixScan               --> github.com/evnix/boltdbweb/web.PrefixScan (3 handlers)
[GIN-debug] GET    /web/_filepath            --> github.com/gin-gonic/gin.(_RouterGroup).createStaticHandler.func1 (3 handlers)
[GIN-debug] HEAD   /web/_filepath            --> github.com/gin-gonic/gin.(_RouterGroup).createStaticHandler.func1 (3 handlers)
[GIN-debug] Listening and serving HTTP on :8080
[GIN] 2016/10/07 - 09:45:53 | 404 |      120.41µs | ::1 |   GET     /web/html/layout.html

Any Idea?

Thanks

**Comment by evnix** [comment]
try URL:  http://localhost:8080/web/html/layout.html  directly after starting the program.

**Comment by ehernandez-xk** [comment]
Hi @evnix I get the same error.

`[GIN] 2016/10/10 - 07:50:30 | 404 |     139.285µs | ::1 |   GET     /web/html/layout.html`

**Comment by PumpkinSeed** [comment]
I got the same error. The problem the following: 
You taked the binary to an other folder, andthis tool couldn't handle it. I made a [pull request](https://github.com/evnix/boltdbweb/pull/2) where you can determine the static files location.

**Comment by fedelibre** [comment]
Unless I'm missing something, I'm hitting the same problem, even if I pulled from github today.
My `web/` dir is empty. Is it supposed to be filled by me? I thought that boltdbweb had a default theme already set...

```
$ boltdbweb --db-name=test.db --port=8088 --static-path=/home/fede/web/golang/boltdbweb-test/web
 INFO[0000] starting boltdb-browser..                    
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /ping                     --> main.main.func1 (3 handlers)
[GIN-debug] GET    /                         --> github.com/evnix/boltdbweb/web.Index (3 handlers)
[GIN-debug] GET    /buckets                  --> github.com/evnix/boltdbweb/web.Buckets (3 handlers)
[GIN-debug] POST   /createBucket             --> github.com/evnix/boltdbweb/web.CreateBucket (3 handlers)
[GIN-debug] POST   /put                      --> github.com/evnix/boltdbweb/web.Put (3 handlers)
[GIN-debug] POST   /get                      --> github.com/evnix/boltdbweb/web.Get (3 handlers)
[GIN-debug] POST   /deleteKey                --> github.com/evnix/boltdbweb/web.DeleteKey (3 handlers)
[GIN-debug] POST   /deleteBucket             --> github.com/evnix/boltdbweb/web.DeleteBucket (3 handlers)
[GIN-debug] POST   /prefixScan               --> github.com/evnix/boltdbweb/web.PrefixScan (3 handlers)
[GIN-debug] GET    /web/*filepath            --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
[GIN-debug] HEAD   /web/*filepath            --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
[GIN-debug] Listening and serving HTTP on :8088
[GIN] 2017/09/27 - 18:23:58 | 404 |     158.188µs |       127.0.0.1 | GET      /web/html/layout.html

```

**Comment by evnix** [comment]
the 'web' directory actually has all the required files. you can check it right here on github

**Comment by fedelibre** [comment]
Ok, forget my last comment. The first command didn't work because I forgot to delete the empty `web` directory in my working directory.
Now everything works as expected, sorry for the noise!
